{% set name = "LFPykit" %}
{% set version = "0.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 9a7ae80ad905bb8dd0eeab8517b43c3d5b4fff2b8766c9d5a36320a7a67bd545

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - numpy
    - scipy
    - meautility

test:
  requires:
    - pytest
    - neuron  # [not win]
    - h5py
    - sympy
  imports:
    - lfpykit
    - lfpykit.tests
  commands:
    - py.test -vsx --pyargs lfpykit

about:
  home: https://github.com/LFPy/LFPykit
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Electrostatic forward models for multicompartment neuron models
  description: |
    LFPykit is a collection of freestanding electrostatic forward models
    facilitating predictions of extracellular potentials, magnetic fields
    and related measurements of neural activity from multicompartment neuron
    models.
  doc_url: https://lfpykit.readthedocs.io/
  dev_url: https://github.com/LFPy/LFPykit

extra:
  recipe-maintainers:
    - espenhgn
