{% set name = "LFPykit" %}
{% set version = "0.3.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 17a6b835305c9ebb9e459c61b58f3423ef2b47e0e66f11c834753976971b6e90

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  build:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6
    - pip
    - numpy
    - scipy
    - meautility

test:
  requires:
    - pytest
    - neuron  # [not win and py<39]
    - h5py
  imports:
    - lfpykit
    - lfpykit.tests
  commands:
    - py.test -vsx --pyargs lfpykit

about:
  home: https://github.com/LFPy/LFPykit
  license: GPL-3.0-only
  license_family: GPL
  license_file: LICENSE
  summary: Electrostatic forward models for multicompartment neuron models
  description: |
    LFPykit is a collection of freestanding electrostatic forward models
    facilitating predictions of extracellular potentials, magnetic fields
    and related measurements of neural activity from multicompartment neuron
    models.
  doc_url: https://lfpykit.readthedocs.io/
  dev_url: https://github.com/LFPy/LFPykit

extra:
  recipe-maintainers:
    - espenhgn
